*&---------------------------------------------------------------------*
*& TABLES
*&---------------------------------------------------------------------*
TABLES:
  /scmtms/d_trqrot,
  /scmtms/d_trqitm,
  /scmtms/d_trqpty,
  /scmtms/d_torrot,
  /scmtms/d_torite,
  /scmtms/d_torpty,
  /scmtms/d_torstp,
  /scmtms/d_torsts.
*&---------------------------------------------------------------------*
*& BOPF
*&---------------------------------------------------------------------*
DATA: "Table
  "/SCMTMS/TRQ
  gt_trq_root               TYPE /scmtms/t_trq_root_k,
  gt_trq_item               TYPE /scmtms/t_trq_item_k,
  gt_trq_party              TYPE /scmtms/t_trq_party_k,
  gt_trq_seal               TYPE /scmtms/t_trq_seal_k,
  gt_trq_mrn                TYPE /scmtms/t_trq_mrn_k,
  gt_trq_lcaddr             TYPE /scmtms/t_trq_lc_address_k,
  gt_trq_docref             TYPE /scmtms/t_trq_docref_k,
  gt_trq_act_route          TYPE /scmtms/t_pln_stage,
  gt_trq_txc_root           TYPE /bobf/t_txc_root_k,
  gt_trq_txc_text           TYPE /bobf/t_txc_txt_k,
  gt_trq_txc_cont           TYPE /bobf/t_txc_con_k,
  gt_trq_item_txc_root      TYPE /bobf/t_txc_root_k,
  gt_trq_item_txc_text      TYPE /bobf/t_txc_txt_k,
  gt_trq_item_txc_cont      TYPE /bobf/t_txc_con_k,
  gt_trq_tcc_root           TYPE /scmtms/t_tcc_root_k,
  gt_trq_tcc_root_rate      TYPE /scmtms/t_tcc_exchangert_k,
  gt_trq_tcc_chrgitem       TYPE /scmtms/t_tcc_chrgitem_k,
  gt_trq_tcc_itemelem       TYPE /scmtms/t_tcc_trchrg_element_k,
  gt_trq_tcc_itemelem_rate  TYPE /scmtms/t_tcc_exchangert_k,
  gt_k_trq_root             TYPE /bobf/t_frw_key,
  gt_kl_trq_tor             TYPE /bobf/t_frw_key_link,
  gt_kl_trq_capa            TYPE /bobf/t_frw_key_link,
  "/SCMTMS/TOR(FU/TU/TO)
  gt_tor_root               TYPE /scmtms/t_tor_root_k,
  gt_tor_item               TYPE /scmtms/t_tor_item_tr_k,
  gt_tor_party              TYPE /scmtms/t_tor_party_k,
  gt_tor_seal               TYPE /scmtms/t_tor_seal_k,
  gt_tor_lcaddr             TYPE /scmtms/t_tor_lc_address_k,
  gt_tor_stop               TYPE /scmtms/t_tor_stop_k,
  gt_tor_stop_first         TYPE /scmtms/t_tor_stop_k,
  gt_tor_stop_last          TYPE /scmtms/t_tor_stop_k,
  gt_tor_succ               TYPE /scmtms/t_tor_stop_succ_k,
  gt_tor_exec               TYPE /scmtms/t_tor_exec_k,
  gt_tor_docref             TYPE /scmtms/t_tor_docref_k,
  gt_tor_stage              TYPE /scmtms/t_tor_stage,
  gt_tor_txc_root           TYPE /bobf/t_txc_root_k,
  gt_tor_txc_text           TYPE /bobf/t_txc_txt_k,
  gt_tor_txc_cont           TYPE /bobf/t_txc_con_k,
  gt_tor_item_txc_root      TYPE /bobf/t_txc_root_k,
  gt_tor_item_txc_text      TYPE /bobf/t_txc_txt_k,
  gt_tor_item_txc_cont      TYPE /bobf/t_txc_con_k,
  gt_tor_tcc_root           TYPE /scmtms/t_tcc_root_k,
  gt_tor_tcc_root_rate      TYPE /scmtms/t_tcc_exchangert_k,
  gt_tor_tcc_chrgitem       TYPE /scmtms/t_tcc_chrgitem_k,
  gt_tor_tcc_itemelem       TYPE /scmtms/t_tcc_trchrg_element_k,
  gt_tor_tcc_itemelem_rate  TYPE /scmtms/t_tcc_exchangert_k,
  gt_k_tor_root             TYPE /bobf/t_frw_key,
  gt_kl_tor_trq             TYPE /bobf/t_frw_key_link,
  gt_kl_tor_capa            TYPE /bobf/t_frw_key_link,
  "/SCMTMS/TOR(BO)
  gt_capa_root              TYPE /scmtms/t_tor_root_k,
  gt_capa_item              TYPE /scmtms/t_tor_item_tr_k,
  gt_capa_party             TYPE /scmtms/t_tor_party_k,
  gt_capa_seal              TYPE /scmtms/t_tor_seal_k,
  gt_capa_lcaddr            TYPE /scmtms/t_tor_lc_address_k,
  gt_capa_stop              TYPE /scmtms/t_tor_stop_k,
  gt_capa_stop_first        TYPE /scmtms/t_tor_stop_k,
  gt_capa_stop_last         TYPE /scmtms/t_tor_stop_k,
  gt_capa_succ              TYPE /scmtms/t_tor_stop_succ_k,
  gt_capa_exec              TYPE /scmtms/t_tor_exec_k,
  gt_capa_docref            TYPE /scmtms/t_tor_docref_k,
  gt_capa_stage             TYPE /scmtms/t_tor_stage,
  gt_capa_txc_root          TYPE /bobf/t_txc_root_k,
  gt_capa_txc_text          TYPE /bobf/t_txc_txt_k,
  gt_capa_txc_cont          TYPE /bobf/t_txc_con_k,
  gt_capa_item_txc_root     TYPE /bobf/t_txc_root_k,
  gt_capa_item_txc_text     TYPE /bobf/t_txc_txt_k,
  gt_capa_item_txc_cont     TYPE /bobf/t_txc_con_k,
  gt_capa_tcc_root          TYPE /scmtms/t_tcc_root_k,
  gt_capa_tcc_root_rate     TYPE /scmtms/t_tcc_exchangert_k,
  gt_capa_tcc_chrgitem      TYPE /scmtms/t_tcc_chrgitem_k,
  gt_capa_tcc_itemelem      TYPE /scmtms/t_tcc_trchrg_element_k,
  gt_capa_tcc_itemelem_rate TYPE /scmtms/t_tcc_exchangert_k,
  gt_k_capa_root            TYPE /bobf/t_frw_key,
  gt_kl_capa_trq            TYPE /bobf/t_frw_key_link,
  gt_kl_capa_tor            TYPE /bobf/t_frw_key_link,
  "/SCMTMS/LOCATION
  gt_loc_root               TYPE /scmtms/t_bo_loc_root_k,
  gt_loc_desc               TYPE /scmtms/t_bo_loc_description_k,
  gt_loc_selected_addr      TYPE /scmtms/t_bo_loc_addr_detailsk,
  gt_k_go_c_root            TYPE /bobf/t_frw_key,
  "/BOFU/BUSINESSPARTNER, /SCMTMS/BUPA
  gt_bupa_root              TYPE /bofu/t_bupa_root_k,
  gt_bupa_common            TYPE /bofu/t_bupa_common_k,
  gt_bupa_text              TYPE /scmtms/t_bp_text_k,
  gt_k_bupa_root            TYPE /bobf/t_frw_key.

DATA: "Work area
  "/SCMTMS/TRQ
  gs_trq_root               TYPE /scmtms/s_trq_root_k,
  gs_trq_item               TYPE /scmtms/s_trq_item_k,
  gs_trq_party              TYPE /scmtms/s_trq_party_k,
  gs_trq_seal               TYPE /scmtms/s_trq_seal_k,
  gs_trq_mrn                TYPE /scmtms/s_trq_mrn_k,
  gs_trq_lcaddr             TYPE /scmtms/s_trq_lc_address_k,
  gs_trq_docref             TYPE /scmtms/s_trq_docref_k,
  gs_trq_act_route          TYPE /scmtms/s_pln_stage,
  gs_trq_txc_root           TYPE /bobf/s_txc_root_k,
  gs_trq_txc_text           TYPE /bobf/s_txc_txt_k,
  gs_trq_txc_cont           TYPE /bobf/s_txc_con_k,
  gs_trq_item_txc_root      TYPE /bobf/s_txc_root_k,
  gs_trq_item_txc_text      TYPE /bobf/s_txc_txt_k,
  gs_trq_item_txc_cont      TYPE /bobf/s_txc_con_k,
  gs_trq_tcc_root           TYPE /scmtms/s_tcc_root_k,
  gs_trq_tcc_root_rate      TYPE /scmtms/s_tcc_exchangert_k,
  gs_trq_tcc_chrgitem       TYPE /scmtms/s_tcc_chrgitem_k,
  gs_trq_tcc_itemelem       TYPE /scmtms/s_tcc_trchrg_element_k,
  gs_trq_tcc_itemelem_rate  TYPE /scmtms/s_tcc_exchangert_k,
  gs_k_trq_root             TYPE /bobf/s_frw_key,
  gs_kl_trq_tor             TYPE /bobf/s_frw_key_link,
  gs_kl_trq_capa            TYPE /bobf/s_frw_key_link,
  "/SCMTMS/TOR(FU/TU/TO)
  gs_tor_root               TYPE /scmtms/s_tor_root_k,
  gs_tor_item               TYPE /scmtms/s_tor_item_tr_k,
  gs_tor_party              TYPE /scmtms/s_tor_party_k,
  gs_tor_seal               TYPE /scmtms/s_tor_seal_k,
  gs_tor_lcaddr             TYPE /scmtms/s_tor_lc_address_k,
  gs_tor_stop               TYPE /scmtms/s_tor_stop_k,
  gs_tor_stop_first         TYPE /scmtms/s_tor_stop_k,
  gs_tor_stop_last          TYPE /scmtms/s_tor_stop_k,
  gs_tor_succ               TYPE /scmtms/s_tor_stop_succ_k,
  gs_tor_exec               TYPE /scmtms/s_tor_exec_k,
  gs_tor_docref             TYPE /scmtms/s_tor_docref_k,
  gs_tor_stage              TYPE /scmtms/s_tor_stage_cmn,
  gs_tor_txc_root           TYPE /bobf/s_txc_root_k,
  gs_tor_txc_text           TYPE /bobf/s_txc_txt_k,
  gs_tor_txc_cont           TYPE /bobf/s_txc_con_k,
  gs_tor_item_txc_root      TYPE /bobf/s_txc_root_k,
  gs_tor_item_txc_text      TYPE /bobf/s_txc_txt_k,
  gs_tor_item_txc_cont      TYPE /bobf/s_txc_con_k,
  gs_tor_tcc_root           TYPE /scmtms/s_tcc_root_k,
  gs_tor_tcc_root_rate      TYPE /scmtms/s_tcc_exchangert_k,
  gs_tor_tcc_chrgitem       TYPE /scmtms/s_tcc_chrgitem_k,
  gs_tor_tcc_itemelem       TYPE /scmtms/s_tcc_trchrg_element_k,
  gs_tor_tcc_itemelem_rate  TYPE /scmtms/s_tcc_exchangert_k,
  gs_k_tor_root             TYPE /bobf/s_frw_key,
  gs_kl_tor_trq             TYPE /bobf/s_frw_key_link,
  gs_kl_tor_capa            TYPE /bobf/s_frw_key_link,
  "/SCMTMS/TOR(BO)
  gs_capa_root              TYPE /scmtms/s_tor_root_k,
  gs_capa_item              TYPE /scmtms/s_tor_item_tr_k,
  gs_capa_party             TYPE /scmtms/s_tor_party_k,
  gs_capa_seal              TYPE /scmtms/s_tor_seal_k,
  gs_capa_lcaddr            TYPE /scmtms/s_tor_lc_address_k,
  gs_capa_stop              TYPE /scmtms/s_tor_stop_k,
  gs_capa_stop_first        TYPE /scmtms/s_tor_stop_k,
  gs_capa_stop_last         TYPE /scmtms/s_tor_stop_k,
  gs_capa_succ              TYPE /scmtms/s_tor_stop_succ_k,
  gs_capa_exec              TYPE /scmtms/s_tor_exec_k,
  gs_capa_docref            TYPE /scmtms/s_tor_docref_k,
  gs_capa_stage             TYPE /scmtms/s_tor_stage_cmn,
  gs_capa_txc_root          TYPE /bobf/s_txc_root_k,
  gs_capa_txc_text          TYPE /bobf/s_txc_txt_k,
  gs_capa_txc_cont          TYPE /bobf/s_txc_con_k,
  gs_capa_item_txc_root     TYPE /bobf/s_txc_root_k,
  gs_capa_item_txc_text     TYPE /bobf/s_txc_txt_k,
  gs_capa_item_txc_cont     TYPE /bobf/s_txc_con_k,
  gs_capa_tcc_root          TYPE /scmtms/s_tcc_root_k,
  gs_capa_tcc_root_rate     TYPE /scmtms/s_tcc_exchangert_k,
  gs_capa_tcc_chrgitem      TYPE /scmtms/s_tcc_chrgitem_k,
  gs_capa_tcc_itemelem      TYPE /scmtms/s_tcc_trchrg_element_k,
  gs_capa_tcc_itemelem_rate TYPE /scmtms/s_tcc_exchangert_k,
  gs_k_capa_root            TYPE /bobf/s_frw_key,
  gs_kl_capa_trq            TYPE /bobf/s_frw_key_link,
  gs_kl_capa_tor            TYPE /bobf/s_frw_key_link,
  "/SCMTMS/LOCATION
  gs_loc_root             TYPE /scmtms/s_bo_loc_root_k,
  gs_loc_desc             TYPE /scmtms/s_bo_loc_description_k,
  gs_loc_selected_addr    TYPE /scmtms/s_bo_loc_addr_detailsk,
  gs_k_locc_root            TYPE /bobf/s_frw_key,
  "/BOFU/BUSINESSPARTNER, /SCMTMS/BUPA
  gs_bupa_root              TYPE /bofu/s_bupa_root_k,
  gs_bupa_common            TYPE /bofu/s_bupa_common_k,
  gs_bupa_text              TYPE /scmtms/s_bp_text_k,
  gs_k_bupa_root            TYPE /bobf/s_frw_key.

FIELD-SYMBOLS: "Field symbols
  "/SCMTMS/TRQ
  <fs_trq_root>               TYPE /scmtms/s_trq_root_k,
  <fs_trq_item>               TYPE /scmtms/s_trq_item_k,
  <fs_trq_party>              TYPE /scmtms/s_trq_party_k,
  <fs_trq_seal>               TYPE /scmtms/s_trq_seal_k,
  <fs_trq_mrn>                TYPE /scmtms/s_trq_mrn_k,
  <fs_trq_lcaddr>             TYPE /scmtms/s_trq_lc_address_k,
  <fs_trq_docref>             TYPE /scmtms/s_trq_docref_k,
  <fs_trq_act_route>          TYPE /scmtms/s_pln_stage,
  <fs_trq_txc_root>           TYPE /bobf/s_txc_root_k,
  <fs_trq_txc_text>           TYPE /bobf/s_txc_txt_k,
  <fs_trq_txc_cont>           TYPE /bobf/s_txc_con_k,
  <fs_trq_item_txc_root>      TYPE /bobf/s_txc_root_k,
  <fs_trq_item_txc_text>      TYPE /bobf/s_txc_txt_k,
  <fs_trq_item_txc_cont>      TYPE /bobf/s_txc_con_k,
  <fs_trq_tcc_root>           TYPE /scmtms/s_tcc_root_k,
  <fs_trq_tcc_root_rate>      TYPE /scmtms/s_tcc_exchangert_k,
  <fs_trq_tcc_chrgitem>       TYPE /scmtms/s_tcc_chrgitem_k,
  <fs_trq_tcc_itemelem>       TYPE /scmtms/s_tcc_trchrg_element_k,
  <fs_trq_tcc_itemelem_rate>  TYPE /scmtms/s_tcc_exchangert_k,
  <fs_k_trq_root>             TYPE /bobf/s_frw_key,
  <fs_kl_trq_tor>             TYPE /bobf/s_frw_key_link,
  <fs_kl_trq_capa>            TYPE /bobf/s_frw_key_link,
  "/SCMTMS/TOR(FU/TU/TO)
  <fs_tor_root>               TYPE /scmtms/s_tor_root_k,
  <fs_tor_item>               TYPE /scmtms/s_tor_item_tr_k,
  <fs_tor_party>              TYPE /scmtms/s_tor_party_k,
  <fs_tor_seal>               TYPE /scmtms/s_tor_seal_k,
  <fs_tor_lcaddr>             TYPE /scmtms/s_tor_lc_address_k,
  <fs_tor_stop>               TYPE /scmtms/s_tor_stop_k,
  <fs_tor_stop_first>         TYPE /scmtms/s_tor_stop_k,
  <fs_tor_stop_last>          TYPE /scmtms/s_tor_stop_k,
  <fs_tor_succ>               TYPE /scmtms/s_tor_stop_succ_k,
  <fs_tor_exec>               TYPE /scmtms/s_tor_exec_k,
  <fs_tor_docref>             TYPE /scmtms/s_tor_docref_k,
  <fs_tor_stage>              TYPE /scmtms/s_tor_stage_cmn,
  <fs_tor_txc_root>           TYPE /bobf/s_txc_root_k,
  <fs_tor_txc_text>           TYPE /bobf/s_txc_txt_k,
  <fs_tor_txc_cont>           TYPE /bobf/s_txc_con_k,
  <fs_tor_item_txc_root>      TYPE /bobf/s_txc_root_k,
  <fs_tor_item_txc_text>      TYPE /bobf/s_txc_txt_k,
  <fs_tor_item_txc_cont>      TYPE /bobf/s_txc_con_k,
  <fs_tor_tcc_root>           TYPE /scmtms/s_tcc_root_k,
  <fs_tor_tcc_root_rate>      TYPE /scmtms/s_tcc_exchangert_k,
  <fs_tor_tcc_chrgitem>       TYPE /scmtms/s_tcc_chrgitem_k,
  <fs_tor_tcc_itemelem>       TYPE /scmtms/s_tcc_trchrg_element_k,
  <fs_tor_tcc_itemelem_rate>  TYPE /scmtms/s_tcc_exchangert_k,
  <fs_k_tor_root>             TYPE /bobf/s_frw_key,
  <fs_kl_tor_trq>             TYPE /bobf/s_frw_key_link,
  <fs_kl_tor_capa>            TYPE /bobf/s_frw_key_link,
  "/SCMTMS/TOR(BO)
  <fs_capa_root>              TYPE /scmtms/s_tor_root_k,
  <fs_capa_item>              TYPE /scmtms/s_tor_item_tr_k,
  <fs_capa_party>             TYPE /scmtms/s_tor_party_k,
  <fs_capa_seal>              TYPE /scmtms/s_tor_seal_k,
  <fs_capa_lcaddr>            TYPE /scmtms/s_tor_lc_address_k,
  <fs_capa_stop>              TYPE /scmtms/s_tor_stop_k,
  <fs_capa_stop_first>        TYPE /scmtms/s_tor_stop_k,
  <fs_capa_stop_last>         TYPE /scmtms/s_tor_stop_k,
  <fs_capa_succ>              TYPE /scmtms/s_tor_stop_succ_k,
  <fs_capa_exec>              TYPE /scmtms/s_tor_exec_k,
  <fs_capa_docref>            TYPE /scmtms/s_tor_docref_k,
  <fs_capa_stage>             TYPE /scmtms/s_tor_stage_cmn,
  <fs_capa_txc_root>          TYPE /bobf/s_txc_root_k,
  <fs_capa_txc_text>          TYPE /bobf/s_txc_txt_k,
  <fs_capa_txc_cont>          TYPE /bobf/s_txc_con_k,
  <fs_capa_item_txc_root>     TYPE /bobf/s_txc_root_k,
  <fs_capa_item_txc_text>     TYPE /bobf/s_txc_txt_k,
  <fs_capa_item_txc_cont>     TYPE /bobf/s_txc_con_k,
  <fs_capa_tcc_root>          TYPE /scmtms/s_tcc_root_k,
  <fs_capa_tcc_root_rate>     TYPE /scmtms/s_tcc_exchangert_k,
  <fs_capa_tcc_chrgitem>      TYPE /scmtms/s_tcc_chrgitem_k,
  <fs_capa_tcc_itemelem>      TYPE /scmtms/s_tcc_trchrg_element_k,
  <fs_capa_tcc_itemelem_rate> TYPE /scmtms/s_tcc_exchangert_k,
  <fs_k_capa_root>            TYPE /bobf/s_frw_key,
  <fs_kl_capa_trq>            TYPE /bobf/s_frw_key_link,
  <fs_kl_capa_tor>            TYPE /bobf/s_frw_key_link,
  "/SCMTMS/LOCATION
  <fs_loc_root>             TYPE /scmtms/s_bo_loc_root_k,
  <fs_loc_desc>             TYPE /scmtms/s_bo_loc_description_k,
  <fs_loc_selected_addr>    TYPE /scmtms/s_bo_loc_addr_detailsk,
  <fs_k_loc_root>             TYPE /bobf/s_frw_key,
  "/BOFU/BUSINESSPARTNER, /SCMTMS/BUPA
  <fs_bupa_root>              TYPE /bofu/s_bupa_root_k,
  <fs_bupa_common>            TYPE /bofu/s_bupa_common_k,
  <fs_bupa_text>              TYPE /scmtms/s_bp_text_k,
  <fs_k_bupa_root>            TYPE /bobf/s_frw_key.

DATA:
  "BOPF
  gv_rejected       TYPE boole_d,
  gt_key            TYPE /bobf/t_frw_key,
  gs_key            TYPE /bobf/s_frw_key,
  gt_failed_key     TYPE /bobf/t_frw_key,
  gs_failed_key     TYPE /bobf/s_frw_key,
  gt_mod            TYPE /bobf/t_frw_modification,
  gs_mod            TYPE /bobf/s_frw_modification,
  gt_changed_fields TYPE /bobf/t_frw_name,
  gv_changed_fields TYPE string,
  go_conf_trq       TYPE REF TO /bobf/if_frw_configuration,
  go_trq_srvmgr     TYPE REF TO /bobf/if_tra_service_manager,
  go_tor_srvmgr     TYPE REF TO /bobf/if_tra_service_manager,
  go_tramgr         TYPE REF TO /bobf/if_tra_transaction_mgr,
  go_change         TYPE REF TO /bobf/if_tra_change,
  go_message        TYPE REF TO /bobf/if_frw_message,
  "FPM
  gt_message        TYPE fpmgb_t_messages,
  gs_message        TYPE fpmgb_s_t100_message,
  gv_result         TYPE fpm_event_result.
